# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-20 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name',
                 models.CharField(blank=True,
                                  help_text='Enter full name or first name.',
                                  max_length=110,
                                  verbose_name='Full name')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'),
                                                                 ('f',
                                                                  'female')],
                                            help_text='Choose a gender.',
                                            max_length=1,
                                            verbose_name='Gender')),
                ('date_of_birth',
                 models.DateField(blank=True,
                                  help_text='Enter the date of birth.',
                                  verbose_name='Date of birth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('defaultmodelfield_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True, primary_key=True,
                     serialize=False,
                     to='core.DefaultModelField')),
                ('name',
                 models.CharField(help_text='Input list name', max_length=50,
                                  verbose_name='List name')),
                ('description',
                 models.TextField(help_text='Enter a list description',
                                  max_length=200)),
            ],
            bases=('core.defaultmodelfield',),
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('defaultmodelfield_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True, primary_key=True,
                     serialize=False,
                     to='core.DefaultModelField')),
                ('description',
                 models.TextField(help_text='Enter a mailing description',
                                  max_length=100)),
                ('shipment_datetime',
                 models.DateTimeField(blank=True, default=None)),
                ('contact_list',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='core.ContactList')),
            ],
            bases=('core.defaultmodelfield',),
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('defaultmodelfield_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True, primary_key=True,
                     serialize=False,
                     to='core.DefaultModelField')),
                ('name', models.CharField(max_length=50,
                                          verbose_name='Name template')),
                ('description', models.TextField(
                    blank=True,
                    help_text='Enter the template description.',
                    max_length=100)),
                ('template', models.TextField()),
            ],
            bases=('core.defaultmodelfield',),
        ),
        migrations.AddField(
            model_name='defaultmodelfield',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mail_template',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.MailTemplate'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_list',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.ContactList'),
        ),
    ]
