# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(
                blank=True,
                help_text='Enter the date of birth.',
                null=True,
                verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='Enter a list description',
                                   max_length=200),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='name',
            field=models.CharField(help_text='Enter a list name',
                                   max_length=50, verbose_name='List name'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='description',
            field=models.TextField(blank=True,
                                   help_text='Enter a mailing description',
                                   max_length=100),
        ),
    ]
